name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: PHP ${{ matrix.php }} (ZTS) Zend MM ${{ matrix.zend-alloc }}
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: false
      matrix:
        php: ['7.2.34', '7.3.26', '7.4.14', '8.0.1']
        zend-alloc: [0, 1]
    env:
      CFLAGS: "-march=x86-64"
      CXXFLAGS: "-march=x86-64"
    steps:
      - uses: actions/checkout@v2

      - name: Install Valgrind
        run: sudo apt-get install valgrind

      - name: Restore PHP build cache
        id: php-build-cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/php
          key: php-build-${{ matrix.php }}-

      - name: Clone php-build repository
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: php-build/php-build
          ref: 09e8c54eb47678415e1315ac8fab7f1403e9caff
          path: php-build

      - name: Compile PHP
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: |
          cd $GITHUB_WORKSPACE/php-build
          ./install-dependencies.sh
          PHP_BUILD_ZTS_ENABLE=on ./bin/php-build ${{ matrix.php }} $GITHUB_WORKSPACE/php

      - name: Build extension
        run: |
          $GITHUB_WORKSPACE/php/bin/phpize
          ./configure --with-php-config=$GITHUB_WORKSPACE/php/bin/php-config
          make install

      - name: Run .phpt tests
        run: USE_ZEND_ALLOC=${{ matrix.zend-alloc }} REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_ARGS="-m --show-diff" make test
